name = "your-worker-name"
type = "javascript"  # Wrangler will automatically handle TypeScript

# Define the entry point of your worker
main = "./dist/index.js"  # Assuming you're compiling TypeScript to JavaScript in a dist folder

# Define the R2 bucket bindings
[[r2_buckets]]
binding = "R2_BUCKET"  # The variable name you'll use in your Worker code
bucket_name = "your-r2-bucket-name"  # The name of your R2 bucket in Cloudflare

# Account and project information
account_id = "your-account-id"  # Your Cloudflare account ID
workers_dev = true  # Set to false if you are deploying to a custom domain

# Build configuration
[build]
command = "npm run build"  # The command to build your project, typically `tsc` or `webpack`